# Generated by Django 3.2.7 on 2021-09-28 11:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(blank=True, choices=[('U', 'Ukraine'), ('P', 'Poland')], max_length=1),
        ),
        migrations.AddField(
            model_name='myuser',
            name='number',
            field=models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='\\+\\d{9, 14}')]),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('kind_of_animal', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=3)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('breed', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField()),
                ('vaccination', models.CharField(blank=True, max_length=40)),
                ('allergies', models.CharField(blank=True, max_length=40)),
                ('state_of_health', models.CharField(blank=True, choices=[('H', 'Healthy'), ('I', 'Ill')], max_length=1)),
                ('disease', models.TextField(blank=True)),
                ('behaviour_disorders', models.CharField(blank=True, choices=[('F', 'Fearfulness'), ('R', 'Rabies')], max_length=1)),
                ('disorders_description', models.TextField(blank=True)),
                ('country', models.CharField(choices=[('U', 'Ukraine'), ('P', 'Poland')], max_length=1)),
                ('city', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
