# Generated by Django 3.2.7 on 2021-10-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_imagepet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='allergies',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='behaviour_disorders',
            field=models.CharField(blank=True, choices=[('F', 'Fearfulness'), ('R', 'Rabies')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='disease',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='disorders_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='state_of_health',
            field=models.CharField(blank=True, choices=[('H', 'Healthy'), ('I', 'Ill')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='vaccination',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='imagepet',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='images', to='dashboard.pet'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(blank=True, choices=[('U', 'Ukraine'), ('P', 'Poland')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
