# Generated by Django 3.2.7 on 2021-10-01 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210928_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='behaviour_disorders',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='disorders_description',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='state_of_health',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='vaccination',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='\\+\\d{9, 14}')]),
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination', models.CharField(blank=True, max_length=40)),
                ('allergies', models.CharField(blank=True, max_length=40)),
                ('state_of_health', models.CharField(blank=True, choices=[('H', 'Healthy'), ('I', 'Ill')], max_length=1)),
                ('disease', models.TextField(blank=True)),
                ('behaviour_disorders', models.CharField(blank=True, choices=[('F', 'Fearfulness'), ('R', 'Rabies')], max_length=1)),
                ('disorders_description', models.TextField(blank=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pet')),
            ],
        ),
    ]
