# Generated by Django 3.2.7 on 2021-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_myuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
