# Generated by Django 3.2.7 on 2021-10-05 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_myuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
