# Generated by Django 3.2.7 on 2021-10-06 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211005_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='\\+\\d{9,14}')]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='country',
            field=models.CharField(choices=[('Ukraine', 'Ukraine'), ('Poland', 'Poland')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='pet',
            name='kind_of_animal',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(default='30-50', max_length=6),
        ),
    ]
