# Generated by Django 3.2.7 on 2021-10-07 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20211006_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='allergies',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='behaviour_disorders',
            field=models.CharField(blank=True, choices=[('F', 'Fearfulness'), ('R', 'Rabies')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='disease',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='disorders_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='state_of_health',
            field=models.CharField(blank=True, choices=[('H', 'Healthy'), ('I', 'Ill')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccination',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='\\+\\d{9, 14}')]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='country',
            field=models.CharField(choices=[('U', 'Ukraine'), ('P', 'Poland')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='kind_of_animal',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.DeleteModel(
            name='Health',
        ),
    ]
