# Generated by Django 3.2.7 on 2021-10-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20211007_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(blank=True, choices=[('ukraine', 'Ukraine'), ('poland', 'Poland'), ('russia', 'Russia')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='country',
            field=models.CharField(choices=[('ukraine', 'Ukraine'), ('polland', 'Poland'), ('russia', 'Russia')], max_length=7),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='pet',
            name='kind_of_animal',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(default='30-50', max_length=10),
        ),
    ]
