# Generated by Django 3.2.7 on 2021-10-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20211007_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='country',
            field=models.CharField(choices=[('Ukraine', 'Ukraine'), ('polland', 'Poland'), ('Russia', 'Russia')], max_length=7),
        ),
    ]
