# Generated by Django 3.2.7 on 2021-10-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20211014_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True),
        ),
    ]
