export const AD = {
    name: '',
    kind_of_animal: '',
    breed: '',
    gender: '',
    age: '',
    days: '',
    size: '',
    bio: '',
    country: '',
    city: '',
    files: {
        main: '',
        photo1: '',
        photo2: '',
        photo3: '',
    },
    health: {
        vaccination: '',
        allergies: '',
        state_of_health: '',
        disease: '',
        behaviour_disorders: '',
        disorders_description: '',
    },
    contacts: {
        name: '',
        phone: '',
        email: '',
        country: '',
        city: '',
    },
}
