export const AD = {
    name: '',
    kind_of_animal: '',
    breed: '',
    gender: '',
    age: '',
    days: '',
    size: '',
    bio: '',
    country: '',
    city: '',
    images: [],
    vaccination: '',
    allergies: '',
    state_of_health: '',
    disease: '',
    behaviour_disorders: '',
    disorders_description: '',
    owner: {
        first_name: '',
        phone: '',
        email: '',
    },
    contacts: {
        contact_name: '',
        contact_phone: '',
        contact_email: '',
        contact_country: '',
        contact_city: '',
    },
}
